version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  
  diary:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
    
